### ISSUE TITLE
We need new transform algorithm

### ISSUE THREAD

**Issue by MaoJianwei** [googollee/eviltransform#16]
data at 2015.10.11

NMEA from GPS source：
lat = 39.5768506
lon = 116.2097481

Real Location (From 1. android API    2. picked by BaiduMap)：
lat = 39.96165504
lon = 116.35180069

If you have any improvement,
Please contact me @ maojianwei2016@126.com
Thank you very much !

**Comment by googollee** [comment]
Fork and write it.
