### ISSUE TITLE
WGS84 or WSG84?

### ISSUE THREAD

**Issue by josh-taylr** [googollee/eviltransform#19]
I want to know if the class named WSGPointer.java in the Java library is a spelling error?

Functions and variables in other libraries that refer to the [World Geodetic System](https://en.wikipedia.org/wiki/World_Geodetic_System) abbreviate it to "WGS".

I know it's a small change to make but it added to confusion about coordinates in geoTest.java being incorrect. I found that pairs of coordinates in WGS84 and GCJ-02 aren't converted to the same location by the Baidu Maps API.

**Comment by fengzee-me** [comment]
It's "WGS", apparently. It's a typo and needs to be refactored.

**Comment by josh-taylr** [comment]
I have limited experience with open source. Is a refactor a fesible and worth while change?

**Comment by fengzee-me** [comment]
By refactor I just mean fix the typo. I've done that and created a pull request. This change will not even affect binary code when compiled, so there's no reason not to make it.

**Comment by googollee** [comment]
Fixed by #21
