### ISSUE TITLE
Mix-up in test data (and algorithm).

### ISSUE THREAD

**Issue by josh-taylr** [googollee/eviltransform#20]
Hello,

I am using the Java port and Baidu Maps API in my Android project. I'm sure those familiar with the Baidu API know that it uses the BD-09 coordinate system and that it provides a way to convert WGS84 and GCJ-02 coordinates to BD-09.

I was using pairs of coordinates from geoTest.java and noticed that converting them to BD-09 with the Baidu API didn't place them at the same position. I demonstrated this in an app that places a marker at two coordinates taken from geoTest.java and where [`CoordinateConverter`](http://wiki.lbsyun.baidu.com/cms/androidsdk/doc/v3_6_1/index.html?com/baidu/mapapi/utils/CoordinateConverter.html) corrects them to. Because the WGS84 and GCJ-02 coordinates represent the same position the corrected markers should be in the same place.

`WSGPointer shanghaiWSGPointer = new WSGPointer(31.1774276, 121.5272106);`
`GCJPointer shanghaiGCJPointer = new GCJPointer(31.17530398364597, 121.531541859215);`

This shows that 1.) the data is mixed up (the WGS points are actually GCJ, and vice-versa) and 2.) the conversion algorithms have a minor bug. In `GCJPointer.java` the delta should be added instead of subtracted and in `WSGPointer.java` the delta should be subtracted instead of added. 

![screenshot_2015-11-25-14-18-57](https://cloud.githubusercontent.com/assets/4213664/11385700/32b6f30a-9380-11e5-941f-83ccccbe7a75.png)

**Comment by josh-taylr** [comment]
After further research, I'm starting to think that the issue could be with what I think is a WGS84 coordinates. Can someone tell me, does [www.maps.google.com](http://www.maps.google.com) use GCJ-02 for locations in China? Is this different when using Google Maps from inside or outside of China?

Looking back, it was crazy to think this issue could have gone unnoticed across all code bases. Sorry.

**Comment by fengzee-me** [comment]
Things change and I haven't been doing any research recently. So I can only give possibilities but not answers:

Google Maps service uses AutoNavi.com (高德 in Chinese) 's data for Chinese region, as far as I knew. So the coordinate system depends on AutoNavi's choice, which is very likely to still be GCJ-02.
