### ISSUE TITLE
Wrong earth radius (ellipsoid semi-major axis) used in distance

### ISSUE THREAD

**Issue by Arthur2e5** [googollee/eviltransform#28]
`distance` is supposed to be fed with some [WGS-84](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84)-like coords, which uses an [Earth ellipsoid](https://en.wikipedia.org/wiki/Earth_ellipsoid) of 6,378,137 meters.

This causes a ~0.118% drift in the result.

**Comment by Artoria2e5** [comment]
@googollee
Your fix seems to change the earthR used in wgs2gcj too, creating an incorrect result. Please use a separate SZ-42 semi-major axis for that function.

**Comment by ale5000-git** [comment]
@Artoria2e5: Hi, is the problem you reported been corrected?

**Comment by Artoria2e5** [comment]
@ale5000-git Nope. Use an older release, or use PRCoords.
