### ISSUE TITLE
publish new npm module to fix wrong main config

### ISSUE THREAD

**Issue by springuper** [googollee/eviltransform#30]
javascript version has a wrong main config in package.json, and now it's been fixed, please publish a new version (v0.1.2) to npm registry.

https://github.com/googollee/eviltransform/commit/066fc53b63ccbf1b0e32088fae880e495a5e66dc

**Comment by thkdog** [comment]
same problem found, no maintaining?

**Comment by googollee** [comment]
Just published v0.2.0 to npm registry with some optimize in js code.
