### ISSUE TITLE
[question]integrate with pyproj

### ISSUE THREAD

**Issue by DeoLeung** [googollee/eviltransform#49]
也许和这个项目不是非常相关, 不好意思:

因为需要转换一些GeoJson和shapely.geometry类型, 不知道有没有pyproj的wgs84, bd09, gcj02的转换设置?

**Comment by Artoria2e5** [comment]
gcj02 和 bd09 整个就是用来整人的，EPSG 能愿意被整给它俩编个号就怪了……

总之当没有比较好。

**Comment by googollee** [comment]
太久没有相应，关闭

**Comment by Artoria2e5** [comment]
设置啊？有些现成东西会搞个 ESGI 的号，在 GIS 软件里面直接可以调。
