### ISSUE TITLE
Phillipines not seen as out of China

### ISSUE THREAD

**Issue by edwinveldhuizen** [googollee/eviltransform#57]
```
"location" : {
    "lat" : 14.5733678,
    "lng" : 120.9824999
},
```

Seems currently to be transformed, while it shouldn't since it is in Manilla, the Philippines

**Comment by googollee** [comment]
This code only checks if the point falls into a rectangle which covers whole China. Checking more exactly is out of the target of this project. You can check the location and only pass the one in China to convert.

If you have a better way to check, welcome to submit a pr.
