### ISSUE TITLE
对于原理的探讨

### ISSUE THREAD

**Issue by MagicFrogSJTU** [googollee/eviltransform#63]
我想问一下，
1. wgs_to_gcj02，这个方式是不是和真实使用的方法完全一致？转换后的gcj02是没有误差的？
2. gcj02_to_wgs84_exact，增加迭代次数，是不是能继续缩减误差，假如到到1e-3以下呢？

**Comment by MagicFrogSJTU** [comment]
现在的开源实现，有好几个版本，哪个的wgs_to_gcj02更靠近事实呢

**Comment by googollee** [comment]
我不是很想回答这种问题。

1. 不知道。我不确定官方现在是不是还在用wgs84，以及官方论文里给出的方法，是不是实际在用的方法。
2. 是的。

**Comment by MagicFrogSJTU** [comment]
> 我不是很想回答这种问题。
> 
> 1. 不知道。我不确定官方现在是不是还在用wgs84，以及官方论文里给出的方法，是不是实际在用的方法。
> 2. 是的。

用e=6378137而不是6378245，有什么说法吗。。
