### ISSUE TITLE
Add R?

### ISSUE THREAD

**Issue by dandv** [googollee/eviltransform#7]
I've just found what appears to be an R version of EvilTransform, plus conversion to and from BD-09:

@caijun's https://github.com/caijun/geoChina

There also seems to be a [paper published about it](http://dssm.unipa.it/CRAN/web/packages/geoChina/geoChina.pdf), unless that PDF was auto-generated from the code.

**Comment by googollee** [comment]
I don't know anything about R. Welcome to pr a R version.

**Comment by Arthur2e5** [comment]
> unless that PDF was auto-generated from the code

That's what literate programming is for.
